package com.roomy.roomy.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.util.UUID;

//Post must be editable
@Entity
public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID postId;// need to be autogenerated
    private long userId;
    private String address;
    private String city;
    private String state;
    private int noOfRequiredRoomates;
    private int noOfFilledRoomates;//default should be zero, can't exceed total required roomates;
    // Need to decide on whether to send post date from frontend or generate it here.
    public UUID getPostId() {
        return postId;
    }

    public long getUserId() {
        return userId;
    }

    public String getAddress() {
        return address;
    }

    public String getCity() {
        return city;
    }

    public String getState() {
        return state;
    }

    public int getNoOfRequiredRoomates() {
        return noOfRequiredRoomates;
    }

    public int getNoOfFilledRoomates() {
        return noOfFilledRoomates;
    }

}
