package com.roomy.roomy.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.springframework.lang.NonNull;

import java.util.UUID;

public class PostWithUserId {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID postId;// need to be autogenerated
    private String address1;
    private String address2;
    @NonNull
    private Long userId; //TODO: userId should not be null.
    private String city;
    private String state;
    private String postBody;
    private String pincode;
    private String gender;
    private int numberOfRoommates;
    private int noOfFilledRoommates;

    public UUID getPostId() {
        return postId;
    }

    public void setPostId(UUID postId) {
        this.postId = postId;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getPostBody() {
        return postBody;
    }

    public void setPostBody(String postBody) {
        this.postBody = postBody;
    }

    public String getPincode() {
        return pincode;
    }

    public void setPincode(String pincode) {
        this.pincode = pincode;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public int getNumberOfRoommates() {
        return numberOfRoommates;
    }

    public void setNumberOfRoommates(int numberOfRoommates) {
        this.numberOfRoommates = numberOfRoommates;
    }

    public int getNoOfFilledRoommates() {
        return noOfFilledRoommates;
    }

    public void setNoOfFilledRoommates(int noOfFilledRoommates) {
        this.noOfFilledRoommates = noOfFilledRoommates;
    }
}
