package com.roomy.roomy.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import org.springframework.lang.NonNull;
import org.springframework.validation.annotation.Validated;

import java.util.Date;
import java.util.UUID;

@Validated
@Entity
public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID postId;// need to be autogenerated
    private long userId; //TODO: userId should not be null.
    private String address;
    private String city;
    private String state;
    private String postBody;
    private int noOfRequiredRoomates;
    private int noOfFilledRoomates;//default should be zero, can't exceed total required roomates;
    private final Date postedDate = new Date();

    public Date getPostedDate() { return postedDate;}

    public UUID getPostId() {
        return postId;
    }
    public long getUserId() {
        return userId;
    }

    public String getAddress() {
        return address;
    }

    public String getCity() {
        return city;
    }

    public String getState() {
        return state;
    }

    public int getNoOfRequiredRoomates() {
        return noOfRequiredRoomates;
    }

    public int getNoOfFilledRoomates() {
        return noOfFilledRoomates;
    }

}
